### PR TITLE
[WIP]Add GitHub workflows to check packages

### PR DESCRIPTION
**Pull request by suhan-paradkar**

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
Well again.. A syntax error...
Here's the logs... https://github.com/suhan-paradkar/ports/runs/3096737383

**Comment by WMCB-Tech** [comment]
Yes. i noticed, somehow, what is the occurrence file output produced by workflow 🤔
> `/home/runner/work/_temp/347d8b4b-8a89-4222-949a-457f47d92a65.sh: line 24: syntax error near unexpected token `file'`

**Comment by suhan-paradkar** [comment]
> what is the occurrence file output produced by workflow

@WMCB-Tech You mean... You need the log file?

**Comment by WMCB-Tech** [comment]
Yea

**Comment by suhan-paradkar** [comment]
@WMCB-Tech here goes...
https://github.com/suhan-paradkar/ports/suites/3266628232/logs

**Comment by suhan-paradkar** [comment]
Also.. looks like the error is in https://github.com/suhan-paradkar/ports#L44

**Comment by suhan-paradkar** [comment]
Once the workflow is set up for Ubuntu, then I plan on setting up workflows for other distros

**Pull request closed without merging**
