### PR TITLE
New Package: NXEngine (BETA)

### PR DESCRIPTION
**Pull request by Yonle**

### CODE REVIEW

**Comment by Yonle** [comment]
Closed because i had a stroke

**Comment by WMCB-Tech** [comment]
lmao

**Comment by GrpeApple** [comment]
`git push --force` lol

**Comment by GrpeApple** [comment]
Also, might wanna add a `.gitignore` there for zip files

**Comment by Yonle** [comment]
Kek

**Comment by GrpeApple** [comment]
cool

**Comment by WMCB-Tech** [comment]
I'm merging this commit after setting up workflow

**Comment by GrpeApple** [comment]
> I'm merging this commit after setting up workflow

cooler

**Pull request closed without merging**
